name: 'my_dbt_project'
version: '1.0.0'
config-version: 2

profile: 'default'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  my_dbt_project:
    bronze:
      +materialized: table
      +file_format: parquet
    silver:
      dimensions:
        +materialized: table
        +file_format: parquet
      facts:
        +materialized: table
        +file_format: parquet
        +partition_by: ['year', 'month', 'day']

    gold:
        +materialized: table
        +file_format: parquet
        +partition_by: ['year', 'month', 'day']
